# site settings
title: Unidorsen
subtitle: Hodowla Psów Rasowych
email: unidorsen@wp.pl
description: Hodowla Psów z zamiłowaniem i pasją do zwierząt
baseurl: # the subpath of your site, e.g. /blog
url: "https://www.unidorsen.pl" # the base hostname & protocol for your site
author: Marcel Bednarczyk
street_address:
city: Rzgów
state: łódzkie
zip_code:
country: Polska
phone: 535 425 189

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/unidorsen/
github_url:
gitlab_url:
googleplus_url: 
instagram_url: https://www.instagram.com/unidorsen/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
